name: VN Stock Daily Automated ML Pipeline

on:
  schedule:
    # Tự động kích hoạt vào lúc 6:00 sáng Thứ 3, Thứ 4, Thứ 5, Thứ 6, Thứ 7 (theo giờ Việt Nam)
  - cron: '0 23 * * 1-5'
  workflow_dispatch: # Cho phép bấm nút chạy thủ công trên giao diện GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn scikit-image joblib requests vnstock
        pip install duckdb==1.5.3
        pip install dbt-core dbt-duckdb==1.5.3

    # Thực thi cào dữ liệu thô
    - name: Execute Data Ingestion (Bronze Layer)
      env:
        VNSTOCK_API_KEY: ${{ secrets.VNSTOCK_API_KEY }}
        MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
      run: python ingest.py

    # dbt biên dịch vòng 1 (Đọc file dbt_project.yml và profiles.yml ngay tại thư mục gốc)
    - name: Execute dbt Transform (Round 1)
      env:
        MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
      run: |
        dbt deps
        dbt run --full-refresh --profiles-dir .

    # Kích hoạt Python AI chấm điểm sắc thái
    - name: Execute AI Sentiment Inference (Giai đoạn 3)
      env:
        MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: python models/sentiment/run_inference.py

    # dbt biên dịch vòng cuối để map toàn bộ nhãn sắc thái vào bảng phẳng
    - name: Execute dbt Transform (Final Round)
      env:
        MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
      run: dbt run --profiles-dir .